version: "3.9"
services:
  node:
    container_name: nestjs-rest-service
    image: ihar13/nestjs-rest-service
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile.node
    networks:
      - custom
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
    links:
      - postgres
    restart: always
    depends_on:
      - postgres
  postgres:
    container_name: rss-postgres
    image: ihar13/rss-postgres
    env_file:
      - .env
    build:
      context: .
      dockerfile: dockerfile.postgres
    networks:
      - custom
    volumes:
      - ./logs:/usr/app/logs
      - ./pgdata:/var/lib/postgresql/data
    ports:
        - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DIALECT: ${DB_DIALECT}
    restart: always

networks:
  custom:
    driver: bridge
    